import Head from "next/head";
import Image from "next/image";
import Banner from "../components/HomePageComponents/Banner";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>YourChoice</title>
        <meta
          className=""
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <main>
          <Banner />
        </main>
      </div>
    </div>
  );
}
